-- -------------------------------------------------------------
-- 
-- File Name: Z:\Documents\Viterbi Algorithm\final\codegen\ConEncoder\hdlsrc\ConEncoder_fixpt.vhd
-- Created: 2021-07-07 20:19:08
-- 
-- Generated by MATLAB 9.4, MATLAB Coder 4.0 and HDL Coder 3.12
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ConEncoder_fixpt
-- Source Path: ConEncoder_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ConEncoder_fixpt_pkg.ALL;

ENTITY ConEncoder_fixpt IS
  PORT( in_rsvd                           :   IN    std_logic_vector(0 TO 9);  -- ufix1 [10]
        size                              :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        out_rsvd                          :   OUT   std_logic_vector(0 TO 19)  -- ufix1 [20]
        );
END ConEncoder_fixpt;


ARCHITECTURE rtl OF ConEncoder_fixpt IS

  -- Signals
  SIGNAL size_unsigned                    : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  size_unsigned <= unsigned(size);

  ConEncoder_fixpt_1_output : PROCESS (in_rsvd, size_unsigned)
    VARIABLE out_rsvd1 : std_logic_vector(0 TO 19);
    VARIABLE tmp : unsigned(3 DOWNTO 0);
    VARIABLE tmp_0 : std_logic_vector(0 TO 5);
    VARIABLE currentState : std_logic_vector(0 TO 5);
    VARIABLE add_temp : vector_of_signed32(0 TO 14);
    VARIABLE cast : vector_of_signed32(0 TO 14);
    VARIABLE sub_cast : vector_of_unsigned6(0 TO 14);
    VARIABLE sub_temp : vector_of_unsigned7(0 TO 14);
    VARIABLE sub_cast_0 : vector_of_signed32(0 TO 14);
    VARIABLE sub_cast_1 : vector_of_signed32(0 TO 14);
    VARIABLE sub_cast_2 : vector_of_unsigned6(0 TO 14);
    VARIABLE sub_cast_3 : vector_of_signed32(0 TO 14);
    VARIABLE sub_cast_4 : vector_of_signed32(0 TO 14);
    VARIABLE sub_cast_5 : vector_of_signed32(0 TO 14);
  BEGIN
    --HDL code generation from MATLAB function: ConEncoder_fixpt
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --                                                                          %
    --           Generated by MATLAB 9.4 and Fixed-Point Designer 6.1           %
    --                                                                          %
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --     out = zeros(1, size*2);
    --     currentState = zeros(1, 6);
    --     while (index <= size)
    currentState := (OTHERS => '0');
    out_rsvd1 := (OTHERS => '0');

    FOR index IN 0 TO 14 LOOP
      add_temp(index) := to_signed(index + 1, 32);
      tmp := unsigned(add_temp(index)(3 DOWNTO 0));
      cast(index) := signed(resize(size_unsigned, 32));
      IF to_signed(index + 1, 32) <= cast(index) THEN 
        sub_cast(index) := resize(tmp & '0', 6);
        sub_temp(index) := resize(sub_cast(index), 7) - to_unsigned(16#01#, 7);
        sub_cast_0(index) := signed(resize(sub_temp(index), 32));
        sub_cast_1(index) := signed(resize(tmp, 32));
        out_rsvd1(to_integer(sub_cast_0(index) - 1)) := in_rsvd(to_integer(sub_cast_1(index) - 1)) XOR (currentState(0) XOR (currentState(1) XOR (currentState(2) XOR currentState(5))));
        sub_cast_2(index) := resize(tmp & '0', 6);
        sub_cast_3(index) := signed(resize(sub_cast_2(index), 32));
        sub_cast_4(index) := signed(resize(tmp, 32));
        out_rsvd1(to_integer(sub_cast_3(index) - 1)) := in_rsvd(to_integer(sub_cast_4(index) - 1)) XOR (currentState(1) XOR (currentState(2) XOR (currentState(4) XOR currentState(5))));
        sub_cast_5(index) := signed(resize(tmp, 32));
        tmp_0(0) := in_rsvd(to_integer(sub_cast_5(index) - 1));
        tmp_0(1 TO 5) := currentState(0 TO 4);
      ELSE 
        tmp_0 := currentState;
      END IF;
      currentState := tmp_0;
    END LOOP;

    out_rsvd <= out_rsvd1;
  END PROCESS ConEncoder_fixpt_1_output;


END rtl;

