/*
 * ConEncoder_wrapper_fixpt.c
 *
 * Code generation for function 'ConEncoder_wrapper_fixpt'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "ConEncoder_fixpt_logger.h"
#include "ConEncoder_wrapper_fixpt.h"
#include "ConEncoder_wrapper_fixpt_hdl_mex_data.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 10,    /* lineNo */
  "ConEncoder_wrapper_fixpt",          /* fcnName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_wrapper_fixpt.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 17,  /* lineNo */
  "ConEncoder_fixpt",                  /* fcnName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 1,   /* lineNo */
  "ConEncoder_fixpt",                  /* fcnName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 5,   /* lineNo */
  "loginputsandoutputs.cpp:51",        /* fcnName */
  "b:\\matlab\\src\\cgir_float2fixed\\src\\loginputsandoutputs.cpp:51"/* pathName */
};

static emlrtBCInfo emlrtBCI = { 1,     /* iFirst */
  10,                                  /* iLast */
  18,                                  /* lineNo */
  83,                                  /* colNo */
  "in",                                /* aName */
  "ConEncoder_fixpt",                  /* fName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m",/* pName */
  0                                    /* checkKind */
};

static emlrtBCInfo b_emlrtBCI = { 1,   /* iFirst */
  10,                                  /* iLast */
  19,                                  /* lineNo */
  62,                                  /* colNo */
  "in",                                /* aName */
  "ConEncoder_fixpt",                  /* fName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m",/* pName */
  0                                    /* checkKind */
};

static emlrtBCInfo c_emlrtBCI = { 1,   /* iFirst */
  10,                                  /* iLast */
  20,                                  /* lineNo */
  37,                                  /* colNo */
  "in",                                /* aName */
  "ConEncoder_fixpt",                  /* fName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m",/* pName */
  0                                    /* checkKind */
};

static emlrtBCInfo d_emlrtBCI = { 1,   /* iFirst */
  20,                                  /* iLast */
  18,                                  /* lineNo */
  16,                                  /* colNo */
  "out",                               /* aName */
  "ConEncoder_fixpt",                  /* fName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m",/* pName */
  3                                    /* checkKind */
};

static emlrtBCInfo e_emlrtBCI = { 1,   /* iFirst */
  20,                                  /* iLast */
  19,                                  /* lineNo */
  16,                                  /* colNo */
  "out",                               /* aName */
  "ConEncoder_fixpt",                  /* fName */
  "Z:\\Documents\\Viterbi Algorithm\\final\\codegen\\ConEncoder\\fixpt\\ConEncoder_fixpt.m",/* pName */
  3                                    /* checkKind */
};

/* Function Definitions */
void ConEncoder_wrapper_fixpt(const emlrtStack *sp, const real_T in[10], real_T
  size, real_T out[20])
{
  int32_T i0;
  real_T d0;
  uint8_T size_in;
  uint8_T in_in[10];
  uint8_T out_out[20];
  uint8_T currentState[6];
  int32_T b_index;
  uint8_T c_index;
  uint8_T b_in_in[6];
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  /*                                                                           % */
  /*            Generated by MATLAB 9.4 and Fixed-Point Designer 6.1           % */
  /*                                                                           % */
  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  for (i0 = 0; i0 < 10; i0++) {
    d0 = muDoubleScalarFloor(in[i0]);
    if (muDoubleScalarIsNaN(d0) || muDoubleScalarIsInf(d0)) {
      d0 = 0.0;
    } else {
      d0 = muDoubleScalarRem(d0, 2.0);
    }

    in_in[i0] = (uint8_T)((uint8_T)(int8_T)d0 & 1);
  }

  d0 = muDoubleScalarFloor(size);
  if (muDoubleScalarIsNaN(d0) || muDoubleScalarIsInf(d0)) {
    d0 = 0.0;
  } else {
    d0 = muDoubleScalarRem(d0, 16.0);
  }

  size_in = (uint8_T)((uint8_T)(int8_T)d0 & 15);
  st.site = &emlrtRSI;

  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  /*                                                                           % */
  /*            Generated by MATLAB 9.4 and Fixed-Point Designer 6.1           % */
  /*                                                                           % */
  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  for (i0 = 0; i0 < 20; i0++) {
    out_out[i0] = 0U;
  }

  /*      out = zeros(1, size*2); */
  for (i0 = 0; i0 < 6; i0++) {
    currentState[i0] = 0U;
  }

  /*      currentState = zeros(1, 6); */
  /*      while (index <= size) */
  b_st.site = &b_emlrtRSI;
  b_st.site = &b_emlrtRSI;
  b_index = 1;
  while (b_index <= size_in) {
    c_index = (uint8_T)b_index;
    i0 = c_index;
    if (!((i0 >= 1) && (i0 <= 10))) {
      emlrtDynamicBoundsCheckR2012b(i0, 1, 10, &emlrtBCI, &st);
    }

    i0 = (uint8_T)((c_index << 1) - 1U) & 127;
    if (!((i0 >= 1) && (i0 <= 20))) {
      emlrtDynamicBoundsCheckR2012b(i0, 1, 20, &d_emlrtBCI, &st);
    }

    out_out[i0 - 1] = (uint8_T)(in_in[c_index - 1] ^ ((uint8_T)(currentState[0] ^
      (uint8_T)((uint8_T)(currentState[1] ^ (uint8_T)((uint8_T)(currentState[2] ^
      currentState[5]) & 1)) & 1)) & 1));
    i0 = c_index;
    if (!((i0 >= 1) && (i0 <= 10))) {
      emlrtDynamicBoundsCheckR2012b(i0, 1, 10, &b_emlrtBCI, &st);
    }

    i0 = c_index << 1;
    if (!((i0 >= 1) && (i0 <= 20))) {
      emlrtDynamicBoundsCheckR2012b(i0, 1, 20, &e_emlrtBCI, &st);
    }

    out_out[i0 - 1] = (uint8_T)(in_in[c_index - 1] ^ ((uint8_T)(currentState[1] ^
      (uint8_T)((uint8_T)(currentState[2] ^ (uint8_T)((uint8_T)(currentState[4] ^
      currentState[5]) & 1)) & 1)) & 1));
    i0 = c_index;
    if (!((i0 >= 1) && (i0 <= 10))) {
      emlrtDynamicBoundsCheckR2012b(i0, 1, 10, &c_emlrtBCI, &st);
    }

    b_in_in[0] = in_in[c_index - 1];
    for (i0 = 0; i0 < 5; i0++) {
      b_in_in[i0 + 1] = currentState[i0];
    }

    for (i0 = 0; i0 < 6; i0++) {
      currentState[i0] = b_in_in[i0];
    }

    b_index++;
    if (*emlrtBreakCheckR2012bFlagVar != 0) {
      emlrtBreakCheckR2012b(&st);
    }
  }

  b_st.site = &c_emlrtRSI;
  c_st.site = &g_emlrtRSI;
  b_ConEncoder_fixpt_logger(&c_st, in_in, size_in, out_out);
  for (i0 = 0; i0 < 20; i0++) {
    out[i0] = out_out[i0];
  }
}

/* End of code generation (ConEncoder_wrapper_fixpt.c) */
